### ISSUE TITLE
Alerts sent infinitely

### ISSUE THREAD

**Issue by pbek** [jokob-sk/Pi.Alert#117]
Still thanks a lot for maintaining this projects!

For a long time now I have the issue that as soon a device goes down or pops up I get alert notifications (in my case 1 email per minute) infinitely.

It should skip repeating notification like set in the config of the device:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/1798101/208059078-4ec56d06-f84d-4e80-b61e-6816619e35b9.png">

## docker-compose.yml

```yml
  pialert:
    image: jokobsk/pi.alert
    networks:
      traefik:
      local:
        ipv4_address: 192.168.1.123
    restart: unless-stopped
    volumes:
      - pialert_db:/home/pi/pialert/db
      - ./pialert/pialert.conf:/home/pi/pialert/config/pialert.conf
      - ./pialert/version.conf:/home/pi/pialert/config/version.conf
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.http.routers.pialert.rule=Host(`my-domain.com`)
      - traefik.http.routers.pialert.tls.certresolver=default
      - traefik.http.routers.pialert.tls=true
      - traefik.http.routers.pialert.middlewares=authelia
      - traefik.http.services.pialert.loadbalancer.server.port=20211
      - traefik.docker.network=server_traefik
```

## pialert.conf

```ini
#-------------------------------------------------------------------------------
#  Pi.Alert
#  Open Source Network Guard / WIFI & LAN intrusion detector 
#
#  pialert.conf - Back module. Configuration file
#-------------------------------------------------------------------------------
#  Puche 2021        pi.alert.application@gmail.com        GNU GPLv3
#-------------------------------------------------------------------------------

# Example: https://github.com/jokob-sk/Pi.Alert/blob/main/config/pialert.conf

PIALERT_PATH      = '/home/pi/pialert'
DB_PATH           = PIALERT_PATH + '/db/pialert.db'
VENDORS_DB        = '/usr/share/arp-scan/ieee-oui.txt'
PRINT_LOG         = False
TIMEZONE          = 'Europe/Vienna'

INCLUDED_SECTIONS       = ['internet', 'new_devices', 'down_devices', 'events']   # Specifies which events trigger notifications.
                                                                                  # Remove the event type(s) you don't want to get notified on
                                                                                  # Overrides device-specific settings in the UI.
SCAN_CYCLE_MINUTES      = 5            # delay between scans

SMTP_SERVER       = 'myserver'
SMTP_PORT         = 587
SMTP_USER         = 'myuser'
SMTP_PASS         = 'secret'

REPORT_MAIL       = True
REPORT_FROM       = 'noreply@mydomain.com'
REPORT_TO         = 'mail@mydomain.com'
REPORT_DEVICE_URL = 'https://mydomain.com/deviceDetails.php?mac='
REPORT_DASHBOARD_URL = 'https://mydomain.com/'

# QUERY_MYIP_SERVER = 'https://diagnostic.opendns.com/myip'
QUERY_MYIP_SERVER = 'http://ipv4.icanhazip.com'
DDNS_ACTIVE       = False
DDNS_DOMAIN       = 'your_domain.freeddns.org'
DDNS_USER         = 'dynu_user'
DDNS_PASSWORD     = 'A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL   = 'https://api.dynu.com/nic/update?'

PIHOLE_ACTIVE     = False
PIHOLE_DB         = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE       = False
DHCP_LEASES       = '/etc/pihole/dhcp.leases'

# arp-scan options & samples
#
# Scan local network (default)
# SCAN_SUBNETS    = '--localnet'
#
# Scan two subnets
# SCAN_SUBNETS    = '192.168.11.0/24 192.168.144.0/24'
#
# Scan using interface eth0
# SCAN_SUBNETS    = '--localnet --interface=eth0'

#SCAN_SUBNETS      = '--localnet'
SCAN_SUBNETS    = '--localnet --interface=eth0'

# cd /home/pi/pialert/config && ./reset_password.sh yournewpassword
# or see https://github.com/jokob-sk/Pi.Alert/issues/38
PIALERT_WEB_PASSWORD = 'PASSWORD HASH'

# Maintenance Task Settings
# ----------------------
DAYS_TO_KEEP_EVENTS = 90
```
