### ISSUE TITLE
Scan doesn't seem to be finishing

### ISSUE THREAD

**Issue by shadowjig** [jokob-sk/Pi.Alert#121]
Scan is running for a long time and never seems to finish.  nginx is running and I get the web interface.  I can see the db file grows a little larger.  It's 180kb.  And log files are generated.  I don't see anything show up in the different sections of the web interface.

**Paste last few lines from `pialert.log`**

```
    Skipping Dynamic DNS update...
Scan Devices
    ScanCycle:1
    Timestamp:2022-12-17 21:57:00

Scanning...
    arp-scan Method...
    arp-scan: One interface
```

**Paste your `pialert.conf` (remove personal info)**
I'm using your example config.  So there's many sections uncommented, but they are not enabled.

```
PRINT_LOG               = False
TIMEZONE                = 'America/New_York'
PIALERT_WEB_PROTECTION  = False
PIALERT_WEB_PASSWORD    = 'password'

INCLUDED_SECTIONS       = ['internet', 'new_devices', 'down_devices', 'events']   # Specifies which events trigger notifications. 
                                                                                  # Remove the event type(s) you don't want to get notified on 
                                                                                  # Overrides device-specific settings in the UI.
SCAN_CYCLE_MINUTES      = 1440            # delay between scans

SCAN_SUBNETS    = '10.1.0.0/16'
```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
```

############################################################################################
###  pialert - Network monitor/intrusion alert/Fing aternative
############################################################################################

version: "3"
networks:
  docker_ip_network:
    external: true
services:
  pialert:
    container_name: pialert
    image: jokobsk/pi.alert:latest
    volumes:
      - /volume1/docker/pialert/config:/home/pi/pialert/config
      - /volume1/docker/pialert/db:/home/pi/pialert/db
      - /volume1/docker/pialert/log:/home/pi/pialert/front/log
      - /volume1/docker/dns_stack/pihole/etc-pihole/pihole-FTL.db:/etc/pihole/pihole-FTL.db:ro
    environment:
      - PUID=<redacted>
      - PGID=<redacted>
      - PORT=80
      - TZ=America/New_York
    networks:
       docker_ip_network:
          ipv4_address: <redacted>
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

```

`.env` 
```

I'm not using any environment variables

```
**Screenshots**
