### ISSUE TITLE
Pi.Alert taking a long time to start with UID/GID defined

### ISSUE THREAD

**Issue by acbgbca** [jokob-sk/Pi.Alert#130]
**Describe the issue**

Pi.Alert is taking a long time to start for me, sometimes several minutes. After some investigation I believe the problem is related to the 'chown' command in user-mapping.sh (line 27)

Investigating further, the reason that command takes so long is that there are '9261' files in the /home/pi/pialert directory:

```
# ls -1 -R . | wc -l
9261
```

The vast majority of files appear to be under /home/pi/pialert/front/lib/AdminLTE (9048), and bower_components within that (8499)

I think the main issue is that the chown should not be required. Unless those files are being edited and/or being stored in a volume, the owner isn't important provided they can be read. Given they are linked under /var/www/html, the owner likely should be www-data.

I believe the simplest solution would be to have the Dockerfile put those files directly under /var/www/html instead of using a symbolic link, then they would not have the owner changed.

**Paste last few lines from `pialert.log`**
n/a

**Paste your `pialert.conf` (remove personal info)**
n/a

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
```

---
version: "2.4"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - ./config:/home/pi/pialert/config
      - ./db/pialert.db:/home/pi/pialert/db/pialert.db
      - ./db/setting_darkmode:/home/pi/pialert/db/setting_darkmode
      - ./log:/home/pi/pialert/log
    environment:
      - TZ=Australia/Melbourne
      - PORT=20211
      - HOST_USER_ID=9001
      - HOST_USER_GID=9001

```

`.env` 
none

**Screenshots**
