### ISSUE TITLE
Use a default db and conf to make compose config easier

### ISSUE THREAD

**Issue by devlincashman** [jokob-sk/Pi.Alert#133]
**Is your feature request related to a problem? Please describe.**
If you use bindmounts with docker compose you often simply bind conf and db related dirs for many apps like so:
```YAML
  pialert:
    container_name: pialert
    image: jokobsk/pi.alert
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./pialert/config:/home/pi/pialert/config
      - ./pialert/db:/home/pi/pialert/db
```
However if you do this with Pi.Alert you'll get errors because the app expects a pre-existing db and conf files instead of adding them on first run like is more common.

instead you need to add conf and db files first, make sure the chmod is set correctly and then map the files individually in like so:
```YAML
  pialert:
    container_name: pialert
    image: jokobsk/pi.alert
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./pialert/config/pialert.conf:/home/pi/pialert/config/pialert.conf
      - ./pialert/pialert.db:/home/pi/pialert/pialert.db
```
This is a less intuitive for those who run large docker compose configs. It would be nice to support both behaviors.

**Describe the solution you'd like**
in Dockerfile COPY over db and conf files as default_ files.

docker entry script checks if user has added db of conf files and if not copies them over.

Can put together a PR for this if interested.

**Describe alternatives you've considered**
Shell script in repo that sets up the expected files for a docker compose config
