### ISSUE TITLE
Problem with sending reports

### ISSUE THREAD

**Issue by segatrsrv** [jokob-sk/Pi.Alert#136]
Hello, there was a problem with sending reports to Telegram. docker image I use the latest one.
Maybe an error in the settings?

Thanks in advance for your help.

**Paste last few lines from `pialert.log`**

```

Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2598, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 307, in main
    email_reporting()
  File "/home/pi/pialert/back/pialert.py", line 1715, in email_reporting
    send_email (mail_text, mail_html)
  File "/home/pi/pialert/back/pialert.py", line 1926, in send_email
    smtp_connection.sendmail (REPORT_FROM, REPORT_TO, msg.as_string())
  File "/usr/lib/python3.9/smtplib.py", line 892, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (554, b'Error: Post "https://api.telegram.org/bot***/sendMessage?disable_web_page_preview=true": dial tcp: lookup api.telegram.org on 127.0.0.11:53: read udp 127.0.0.1:39834->127.0.0.11:53: i/o timeout')
mkdir: cannot create directory '/run/php': File exists

```

**Paste your `pialert.conf` (remove personal info)**

```

#-------------------------------------------------------------------------------
#  Pi.Alert
#  Open Source Network Guard / WIFI & LAN intrusion detector 
#
#  pialert.conf - Back module. Configuration file
#-------------------------------------------------------------------------------
#  Puche 2021        pi.alert.application@gmail.com        GNU GPLv3
#-------------------------------------------------------------------------------

# GENERAL settings
# ----------------------

PRINT_LOG               = False
TIMEZONE                = '*******'
PIALERT_WEB_PROTECTION  = False
PIALERT_WEB_PASSWORD    = '***************************************'

INCLUDED_SECTIONS       = ['internet', 'new_devices', 'down_devices', 'events']   # Specifies which events trigger notifications. 
                                                                                  # Remove the event type(s) you don't want to get notified on 
                                                                                  # Overrides device-specific settings in the UI.
SCAN_CYCLE_MINUTES      = 5            # delay between scans

# EMAIL settings
# ----------------------
SMTP_SERVER             = '172.23.0.30'
SMTP_PORT               = 2525
SMTP_USER               = 'use2r@gmail.com'
SMTP_PASS               = 'password'
SMTP_SKIP_TLS           = True
SMTP_SKIP_LOGIN         = True

REPORT_MAIL             = True
REPORT_FROM             = 'Pi.Alert <' + SMTP_USER +'>'
REPORT_TO               = 'user@gmail.com'
REPORT_DEVICE_URL       = 'http://pi.alert/deviceDetails.php?mac='
REPORT_DASHBOARD_URL    = 'http://pi.alert/'

# Webhook settings
# ----------------------
REPORT_WEBHOOK          = False
WEBHOOK_URL             = 'http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD         = 'json'       # webhook payload data format for the "body > attachements > text" attribute 
                                       # in https://github.com/jokob-sk/Pi.Alert/blob/main/docs/webhook_json_sample.json 
                                       #   supported values: 'json', 'html' or 'text'
                                       #   e.g.: for discord use 'html'
WEBHOOK_REQUEST_METHOD  = 'GET'        # POST, GET...

# Apprise settings
#-----------------------
REPORT_APPRISE          = False
APPRISE_HOST            = 'http://localhost:8000/notify'
APPRISE_URL             = 'mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'

# NTFY (https://ntfy.sh/) settings
# ----------------------
REPORT_NTFY             = False
NTFY_HOST               = 'https://ntfy.sh'
NTFY_TOPIC              = 'replace_my_secure_topicname_91h889f28'
NTFY_USER               = 'user'       # set username... 
NTFY_PASSWORD           = 'passw0rd'   # ...and password if authentication is used https://docs.ntfy.sh/config/#users-and-roles

# PUSHSAFER (https://www.pushsafer.com/) settings
# ----------------------
REPORT_PUSHSAFER        = False
PUSHSAFER_TOKEN         = 'ApiKey'

# MQTT settings
# ----------------------
REPORT_MQTT             = False
MQTT_BROKER             = '192.168.1.2'
MQTT_PORT               = 1883
MQTT_USER               = 'mqtt'
MQTT_PASSWORD           = 'passw0rd'
MQTT_QOS                = 0
MQTT_DELAY_SEC          = 2            # delay in seconds, increase if not all devices are created in Home Assistant

# DynDNS
# ----------------------
# QUERY_MYIP_SERVER       = 'https://diagnostic.opendns.com/myip'
QUERY_MYIP_SERVER       = 'http://ipv4.icanhazip.com'
DDNS_ACTIVE             = False
DDNS_DOMAIN             = 'your_domain.freeddns.org'
DDNS_USER               = 'dynu_user'
DDNS_PASSWORD           = 'A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL         = 'https://api.dynu.com/nic/update?'

# PIHOLE settings
# ----------------------
PIHOLE_ACTIVE           = False                         # if enabled you need to map '/etc/pihole/pihole-FTL.db' in docker-compose.yml
PIHOLE_DB               = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE             = False                         # if enabled you need to map '/etc/pihole/dhcp.leases' in docker-compose.yml
DHCP_LEASES             = '/etc/pihole/dhcp.leases'

# arp-scan options & samples
# ----------------------
#
# Scan local network (default)
# SCAN_SUBNETS    = '--localnet'
#
# Scan two subnets
# SCAN_SUBNETS    = '192.168.11.0/24 192.168.144.0/24'
#
# Scan using interface eth0
# SCAN_SUBNETS    = '--localnet --interface=eth0'
#
# Scan multiple interfaces (eth1 and eth0):
# SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]

SCAN_SUBNETS            = '--localnet'

# Maintenance Task Settings
# ----------------------
DAYS_TO_KEEP_EVENTS = 90


```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
```

version: '3.5'
services:

#Pi-hole
  PiHole:
    container_name: PiHole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8880:80/tcp
      - 4443:443/tcp
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PI_HOLE_PASSWORD}
    volumes:
      - ${USERDIR}/pihole/etc-pihole:/etc/pihole
      - ${USERDIR}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      default:
        ipv4_address: 172.23.0.2

#PiAlert
  pialert:
    container_name: PiAlert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: always
    volumes:
      - ${USERDIR}/pialert/config:/home/pi/pialert/config
      - ${USERDIR}/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
      - ${USERDIR}/pihole/etc-pihole/pihole-FTL.db:/etc/pihole/pihole-FTL.db
    environment:
      TZ: ${TZ}
      PORT: 20211
      HOST_USER_ID: ${LOCAL_USER}
      HOST_USER_GID: ${LOCAL_USER}

#SMTP_to_Telegram
  smtp_to_telegram:
    image: kostyaesmukov/smtp_to_telegram
    container_name: SMTP_to_Telegram
    restart: always
    environment:
      ST_TELEGRAM_CHAT_IDS: ${TELEGRAM_CHATID}
      ST_TELEGRAM_BOT_TOKEN: ${TELEGRAM_TOKEN}
      ST_TELEGRAM_MESSAGE_TEMPLATE: "Subject: {subject}\\n\\n{body}"
    networks:
      default:
        ipv4_address: 172.23.0.30

networks:
  default:
    name: guard
    external: false
    ipam:
     driver: default
     config:
       - subnet: 172.23.0.0/24
```
