### ISSUE TITLE
Device detail page has no information any more

### ISSUE THREAD

**Issue by pbek** [jokob-sk/Pi.Alert#143]
**Describe the issue**

Thank you for maintaining Pi.Alert, @jokob-sk!

Since one of the last versions I've the issue that the device detail pages don't show any information any more...
I can store new information, but it never gets shown. I can't see any relevant issues in the browser log (only a "history push" permission issue) nor can I see any failed API requests. Nothing in the `pialert.log` either...

Do you maybe have any clues what has happened?

**Paste last few lines from `pialert.log`**

```
Nothing to do here.

sed: cannot rename /home/pi/pialert/config/pialert.conf: Device or resource busy

Starting nginx: nginx.
```

**Paste your `pialert.conf` (remove personal info)**

```
#-------------------------------------------------------------------------------
#  Pi.Alert
#  Open Source Network Guard / WIFI & LAN intrusion detector 
#
#  pialert.conf - Back module. Configuration file
#-------------------------------------------------------------------------------
#  Puche 2021        pi.alert.application@gmail.com        GNU GPLv3
#-------------------------------------------------------------------------------

# Example: https://github.com/jokob-sk/Pi.Alert/blob/main/config/pialert.conf

PIALERT_PATH      = '/home/pi/pialert'
DB_PATH           = PIALERT_PATH + '/db/pialert.db'
VENDORS_DB        = '/usr/share/arp-scan/ieee-oui.txt'
PRINT_LOG         = False
TIMEZONE          = 'Europe/Vienna'

INCLUDED_SECTIONS       = ['internet', 'new_devices', 'down_devices', 'events']   # Specifies which events trigger notifications.
                                                                                  # Remove the event type(s) you don't want to get notified on
                                                                                  # Overrides device-specific settings in the UI.
SCAN_CYCLE_MINUTES      = 5            # delay between scans

SMTP_SERVER       = 'mail.redacted.com'
SMTP_PORT         = 587
SMTP_USER         = 'noreply@redacted.com'
SMTP_PASS         = 'secret'

REPORT_MAIL       = True
REPORT_FROM       = 'noreply@redacted.com'
REPORT_TO         = 'email@redacted.com'
REPORT_DEVICE_URL = 'https://pialert.redacted.com/deviceDetails.php?mac='
REPORT_DASHBOARD_URL = 'https://pialert.redacted.com/'

# Webhook settings
# ----------------------
REPORT_WEBHOOK          = False
WEBHOOK_URL             = 'http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD         = 'json'       # webhook payload data format for the "body > attachements > text" attribute
                                       # in https://github.com/jokob-sk/Pi.Alert/blob/main/docs/webhook_json_sample.json
                                       #   supported values: 'json', 'html' or 'text'
                                       #   e.g.: for discord use 'html'
WEBHOOK_REQUEST_METHOD  = 'GET'        # POST, GET...

# Apprise settings
#-----------------------
REPORT_APPRISE          = False
APPRISE_HOST            = 'http://localhost:8000/notify'
APPRISE_URL             = 'mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'

# NTFY (https://ntfy.sh/) settings
# ----------------------
REPORT_NTFY             = False
NTFY_HOST               = 'https://ntfy.sh'
NTFY_TOPIC              = 'replace_my_secure_topicname_91h889f28'
NTFY_USER               = 'user'       # set username...
NTFY_PASSWORD           = 'passw0rd'   # ...and password if authentication is used https://docs.ntfy.sh/config/#users-and-roles

# PUSHSAFER (https://www.pushsafer.com/) settings
# ----------------------
REPORT_PUSHSAFER        = False
PUSHSAFER_TOKEN         = 'ApiKey'

# MQTT settings
# ----------------------
REPORT_MQTT             = False
MQTT_BROKER             = '192.168.1.2'
MQTT_PORT               = 1883
MQTT_USER               = 'mqtt'
MQTT_PASSWORD           = 'passw0rd'
MQTT_QOS                = 0
MQTT_DELAY_SEC          = 2            # delay in seconds, increase if not all devices are created in Home Assistant

# DynDNS
# ----------------------
# QUERY_MYIP_SERVER       = 'https://diagnostic.opendns.com/myip'
QUERY_MYIP_SERVER       = 'http://ipv4.icanhazip.com'
DDNS_ACTIVE             = False
DDNS_DOMAIN             = 'your_domain.freeddns.org'
DDNS_USER               = 'dynu_user'
DDNS_PASSWORD           = 'A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL         = 'https://api.dynu.com/nic/update?'

# PIHOLE settings
# ----------------------
PIHOLE_ACTIVE           = False
PIHOLE_DB               = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE             = False
DHCP_LEASES             = '/etc/pihole/dhcp.leases'

# arp-scan options & samples
#
# Scan local network (default)
# SCAN_SUBNETS    = '--localnet'
#
# Scan two subnets
# SCAN_SUBNETS    = '192.168.11.0/24 192.168.144.0/24'
#
# Scan using interface eth0
# SCAN_SUBNETS    = '--localnet --interface=eth0'

#SCAN_SUBNETS      = '--localnet'
SCAN_SUBNETS    = '--localnet --interface=eth0'

# cd /home/pi/pialert/config && ./reset_password.sh yournewpassword
# or see https://github.com/jokob-sk/Pi.Alert/issues/38
PIALERT_WEB_PASSWORD = 'PASSWORD HASH'

# Maintenance Task Settings
# ----------------------
DAYS_TO_KEEP_EVENTS = 90

```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
```
  pialert:
    image: jokobsk/pi.alert
    networks:
      traefik:
      local:
        ipv4_address: 192.168.1.123
    restart: unless-stopped
    volumes:
      - pialert_db:/home/pi/pialert/db
      # https://github.com/jokob-sk/Pi.Alert/blob/main/config/pialert.conf
      - ./pialert/pialert.conf:/home/pi/pialert/config/pialert.conf
      - ./pialert/version.conf:/home/pi/pialert/config/version.conf
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.http.routers.pialert.rule=Host(`pialert.redacted.com`)
      - traefik.http.routers.pialert.tls.certresolver=default
      - traefik.http.routers.pialert.tls=true
      - traefik.http.routers.pialert.middlewares=authelia
      - traefik.http.services.pialert.loadbalancer.server.port=20211
      - traefik.docker.network=server_traefik
```

**Screenshots**

<img width="876" alt="image" src="https://user-images.githubusercontent.com/1798101/212033057-06ab62ea-e51f-450a-9492-dd343701e700.png">
