### ISSUE TITLE
Problem with sending reports through google SMTP server

### ISSUE THREAD

**Issue by gminadak** [jokob-sk/Pi.Alert#145]
**Describe the issue**
Hello and thank you for all the effort you have put on this software and for continuing improving it with new features.
For some time now I have stop receiving reports from Pi.alert here is my configuration.
From the logs I can see that it can't connect to SMTP but I can't see the reason (e.g. wrong password, can't reach server etc).

**Paste last few lines from `pialert.log`**

```

[2023-01-21 11:13:42] START Test: REPORT_MAIL
[PRINT_LOG] 2023-01-21 11:13:42.576242 0:00:10.012989 REPORT_TO: s***************g@gmail.com  SMTP_USER: s***************g@gmail.com
      ERROR: Couldn't connect to the SMTP server, skipping Email
[2023-01-21 11:13:43] END Test: REPORT_MAIL

```

**Paste your `pialert.conf` (remove personal info)**

![Screenshot 2023-01-21 112115](https://user-images.githubusercontent.com/45330594/213860842-7d3ed3be-46c2-474f-91da-06559ec05c84.png)

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
```

version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: always
    volumes:
      - ${APP_DATA_LOCATION}/pialert/config:/home/pi/pialert/config
      - ${APP_DATA_LOCATION}/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
      # (optional) map an empty file with the name 'setting_darkmode' if you want to force the dark mode on container rebuilt
      - ${APP_DATA_LOCATION}/pialert/db/setting_darkmode:/home/pi/pialert/db/setting_darkmode
      # (optional) useful for debugging if you have issues setting up the container
      - ${LOGS_LOCATION}:/home/pi/pialert/log
      # comment out below 2 lines, they are only for development purposes
#      - ${DEV_LOCATION}/back/pialert.py:/home/pi/pialert/back/pialert.py
#      - ${DEV_LOCATION}/front:/home/pi/pialert/front
    environment:
      - TZ=${TZ}
      - PORT=${PORT}
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_USER_GID=${HOST_USER_GID}

```

Both POP/IMAP is ENABLED from Google
![Screenshot 2023-01-21 113652](https://user-images.githubusercontent.com/45330594/213861221-b17ab941-edc8-4ccf-a1b8-83dab9150501.png)
