### ISSUE TITLE
Devices not loaded with 23.01.22 version

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/Pi.Alert#147]
**Describe the issue**

With the last update 23.01.22 the Devices page broke. On the devices page it keeps loading without displaying any devices. I tried with different browsers. Here is the screenshot

**My customizzation in `pialert.conf (192.168.2.2 is my Fritxbox router)`** 
```
SCAN_SUBNETS = '192.168.2.2/24 --interface=eth0'
```

`docker-compose.yml` 
```
version: "3"
services:
  pialert:
    container_name: pialert
    hostname: pialert
    image: jokobsk/pi.alert:latest
    ports:
      - 20211:20211
    network_mode: "host"
    restart: always
    volumes:
      - /home/pi/docker/pialert/config:/home/pi/pialert/config
      - /home/pi/docker/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
      - /home/pi/docker/pialert/log:/home/pi/pialert/log
    environment:
      - TZ=Europe/Rome
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
```

**Screenshots**

![Cattura1](https://user-images.githubusercontent.com/5001932/213914476-817b6602-7701-4599-b671-742ed424b914.PNG)

Log attached
[log.txt](https://github.com/jokob-sk/Pi.Alert/files/10474344/log.txt)

Thanks in advance
PC
