### ISSUE TITLE
not able to map db location to local storage

### ISSUE THREAD

**Issue by docfactory37** [jokob-sk/Pi.Alert#16]
Hey,

Whne i try and map the DB location to local storage iget the below error

![image](https://user-images.githubusercontent.com/20963053/176370631-3338392f-6f34-4610-b10f-9282285c92ad.png)

when i dont map it to local storage pialert all work with no issue.

not sure if its a permssion issue the is not set in the continer to allow to make to local storage

i have also set the local folder that im storing the local files to 777 as i though it was a issue with permsion on local folder but that has not fixed the issue.

if you need any more information please let me know.

**Comment by jokob-sk** [comment]
Hey! 
Can you try to set the permissions on the local file system on the `pialert.db` file directly? Also, in your docker-compose, please try to map the file directly, not the whole `/db` folder (e.g. see this [example](https://github.com/jokob-sk/Pi.Alert/tree/permission-mapping/dockerfiles#example-1)).

**Comment by docfactory37** [comment]
Hey,

Thank you for the quick response.

so i have used you example as below

```
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: always
    volumes:
      - /dockerData/pialert/config:/home/pi/pialert/config
      - /dockerData/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
      - /dockerData/pialert/logs:/home/pi/pialert/log
    environment:
      - TZ=Australia/Sydney
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
```
i have set the complete folder permssion to pi user and 777 

![image](https://user-images.githubusercontent.com/20963053/176393804-17e5dbb4-6b8f-4293-a80e-7567988aa29a.png)


![image](https://user-images.githubusercontent.com/20963053/176392680-6a9fa718-910e-4747-9f42-76cab5b51810.png)
