### ISSUE TITLE
Sign Out doesn't work

### ISSUE THREAD

**Issue by vladaurosh** [jokob-sk/Pi.Alert#181]
**Describe the issue**
Sign Out doesn't work in latest docker image. Sign in works ok, but then clicking on Sign Out just refreshes the page

**Paste last few lines from `pialert.log`**

```

N/A

```

**Paste your `pialert.conf` (remove personal info)**

```
PIALERT_WEB_PROTECTION=True
PIALERT_WEB_PASSWORD='xxxxxxxxxxxxxxxxxxxxxxx'

```
Rest is default.

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
```
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=Europe/Dublin
      - HOST_USER_ID=1001
      - HOST_USER_GID=1001
      - PORT=20211
    volumes:
      - /opt/pi.alert/config:/home/pi/pialert/config
      - /opt/pi.alert/db:/home/pi/pialert/db
```

`.env` 
```

N/A

```
**Screenshots**
