### ISSUE TITLE
High CPU utilization in recent build.

### ISSUE THREAD

**Issue by iAmSaugata** [jokob-sk/Pi.Alert#191]
**Describe the issue**
High CPU utilization in recent build.

![image](https://user-images.githubusercontent.com/26755120/222944059-4d00de1b-dcc2-4873-9c11-651402095c9a.png)

logs TAB from web interface not opening. (Error code: SBOX_FATAL_MEMORY_EXCEEDED)
![image](https://user-images.githubusercontent.com/26755120/222944130-70741c0e-58c7-493b-862d-261bf5ea0c45.png)

**Paste last few lines from `pialert.log`**

```

paste here

```

**Paste your `pialert.conf` (remove personal info)**

```

paste here

```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
```

#Name : pialert
version: '3.5'
services:
  dozzle:
    image: 'jokobsk/pi.alert:latest'
    container_name: 'pialert'
    hostname: 'pialert.lan'  
    volumes:
      - '/home/pi/pi-alert/config:/home/pi/pialert/config'
      - '/home/pi/pi-alert/db/pialert.db:/home/pi/pialert/db/pialert.db'
      - '/home/pi/pi-alert/logs:/home/pi/pialert/front/log'
      - '/home/pi/pi-alert/config/pialert.conf:/home/pi/pialert/config/pialert.conf'
      # Time Zone Sync
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    dns:
      - '192.168.29.50'
    ports:
      - '20211:20211'
    restart: 'always'
    network_mode: "host"

```

`.env` 
```

paste here

```
**Screenshots**
