### ISSUE TITLE
Pi alert show a device with a lot of mac address

### ISSUE THREAD

**Issue by VThang** [jokob-sk/Pi.Alert#202]
**Describe the issue**
After some issue with network of Docker host machine. Pi alert show a device with a lot of mac address and no way to delete.

**Paste last few lines from `pialert.log`**

```

[2023-03-24 15:10:21] Notifications: 0
[2023-03-24 15:10:21] Last action: network_scan
[2023-03-24 15:10:21] Process: Wait
     [API] Updating files in /front/api
[2023-03-24 15:10:26] Process: Start
[2023-03-24 15:10:26] Process: Wait
     [API] Updating files in /front/api
     [API] Updating files in /front/api
     [API] Updating files in /front/api
     [API] Updating files in /front/api
     [API] Updating files in /front/api
     [API] Updating files in /front/api

```

**Paste your `pialert.conf` (remove personal info)**

```

#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2023-03-23_10-12-02            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/Pi.Alert          #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#


# General
#---------------------------
ENABLE_ARPSCAN=True
SCAN_SUBNETS=['192.168.1.0/24 --interface=ens18','192.168.0.0/24 --interface=ens18']
LOG_LEVEL='verbose'
TIMEZONE='xxxxx'
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD='xxxxx'
INCLUDED_SECTIONS=['internet','new_devices','down_devices','events']
SCAN_CYCLE_MINUTES=5
DAYS_TO_KEEP_EVENTS=90
REPORT_DASHBOARD_URL='http://pi.alert/'
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'
UI_LANG='English'


# Email
#---------------------------
REPORT_MAIL=False
SMTP_SERVER='smtp.gmail.com'
SMTP_PORT=587
REPORT_TO='user@gmail.com'
REPORT_FROM='Pi.Alert <user@gmail.com>'
SMTP_SKIP_LOGIN=False
SMTP_USER='user@gmail.com'
SMTP_PASS='password'
SMTP_SKIP_TLS=False
SMTP_FORCE_SSL=False


# Webhooks
#---------------------------
REPORT_WEBHOOK=False
WEBHOOK_URL='http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD='json'
WEBHOOK_REQUEST_METHOD='GET'


# Apprise
#---------------------------
REPORT_APPRISE=False
APPRISE_HOST='http://localhost:8000/notify'
APPRISE_URL='mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'
APPRISE_PAYLOAD='html'


# NTFY
#---------------------------
REPORT_NTFY=False
NTFY_HOST='https://ntfy.sh'
NTFY_TOPIC='replace_my_secure_topicname_91h889f28'
NTFY_USER='user'
NTFY_PASSWORD='passw0rd'


# PUSHSAFER
#---------------------------
REPORT_PUSHSAFER=False
PUSHSAFER_TOKEN='ApiKey'


# MQTT
#---------------------------
REPORT_MQTT=False
MQTT_BROKER='192.168.1.2'
MQTT_PORT=1883
MQTT_USER='mqtt'
MQTT_PASSWORD='passw0rd'
MQTT_QOS=0
MQTT_DELAY_SEC=2


# DynDNS
#---------------------------
DDNS_ACTIVE=False
DDNS_DOMAIN='your_domain.freeddns.org'
DDNS_USER='dynu_user'
DDNS_PASSWORD='A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL='https://api.dynu.com/nic/update?'


# PiHole
#---------------------------
PIHOLE_ACTIVE=False
DHCP_ACTIVE=False


# Pholus
#---------------------------
PHOLUS_ACTIVE=True
PHOLUS_TIMEOUT=120
PHOLUS_FORCE=False
PHOLUS_RUN='schedule'
PHOLUS_RUN_TIMEOUT=600
PHOLUS_RUN_SCHD='0 4 * * *'
PHOLUS_DAYS_DATA=7


# Nmap
#---------------------------
NMAP_ACTIVE=True
NMAP_TIMEOUT=150
NMAP_RUN='none'
NMAP_RUN_SCHD='0 2 * * *'
NMAP_ARGS='-p -10000'


# API
#---------------------------
API_CUSTOM_SQL='SELECT * FROM Devices WHERE dev_PresentLastScan = 0'


# WEBMON
#---------------------------
WEBMON_RUN='disabled'
WEBMON_CMD='python3 /home/pi/pialert/front/plugins/website_monitor/script.py urls={urls}'
WEBMON_RUN_SCHD='0 2 * * *'
WEBMON_API_SQL='SELECT * FROM plugin_website_monitor'
WEBMON_RUN_TIMEOUT=5
WEBMON_WATCH=['Watched_Value1']
WEBMON_REPORT_ON=['new','watched-changed']
WEBMON_urls_to_check=['https://google.com','https://duck.com']
WEBMON_SQL_internet_ip='SELECT dev_LastIP FROM Devices WHERE dev_MAC = {s-quote}Internet{s-quote}'


# NMAPSRV
#---------------------------
NMAPSRV_RUN='disabled'
NMAPSRV_CMD='SELECT  dv.dev_Name as Object_PrimaryID, cast({s-quote}http://{s-quote} || dv.dev_LastIP as VARCHAR(100)) || {s-quote}:{s-quote} || cast( SUBSTR(ns.Port ,0, INSTR(ns.Port , {s-quote}/{s-quote})) as VARCHAR(100)) as Object_SecondaryID,  datetime() as DateTime,  ns.Service as Watched_Value1,        ns.State as Watched_Value2,        {s-quote}null{s-quote} as Watched_Value3,        {s-quote}null{s-quote} as Watched_Value4,        ns.Extra as Extra, dv.dev_MAC as ForeignKey        FROM (SELECT * FROM Nmap_Scan) ns LEFT JOIN (SELECT dev_Name, dev_MAC, dev_LastIP FROM Devices) dv   ON ns.MAC = dv.dev_MAC'
NMAPSRV_RUN_SCHD='0 2 * * *'
NMAPSRV_WATCH=['Watched_Value1']
NMAPSRV_REPORT_ON=['new','watched-changed']


#-------------------IMPORTANT INFO-------------------#
#   This file is ingested by a python script, so if  #
#        modified it needs to use python syntax      #
#-------------------IMPORTANT INFO-------------------#


```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
```

version: "3.9"

networks:
  default:
    driver: bridge
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"
    restart: unless-stopped
    network_mode: "host"
    # networks:
    #   - host
    #   - traefik-proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/vthang/docker/pialert/config:/home/pi/pialert/config
      - /home/vthang/docker/pialert/data/:/home/pi/pialert/db/
      # (optional) useful for debugging if you have issues setting up the container
      - /home/vthang/docker/pialert/log:/home/pi/pialert/front/log
     environment:
      - TZ=${TZ}      
    #   - HOST_USER_ID=${HOST_USER_ID}
    #   - HOST_USER_GID=${HOST_USER_GID}
    #   - PORT=${PORT}
    ports:
      - "20211:20211"

```

`.env` 
```

#GLOBAL PATH VARIABLES

# APP_DATA_LOCATION=/path/to/docker_appdata
# APP_CONFIG_LOCATION=/path/to/docker_config
# LOGS_LOCATION=/path/to/docker_logs

#ENVIRONMENT VARIABLES

TZ=Asia/Ho_Chi_Minh
# HOST_USER_ID=1000
# HOST_USER_GID=1000
# PORT=20211

#DEVELOPMENT VARIABLES

# DEV_LOCATION=/path/to/local/source/code

```
**Screenshots**

![1](https://user-images.githubusercontent.com/10020303/227567779-279c15e3-292f-4345-8caa-5fe6294666fe.png)
![2](https://user-images.githubusercontent.com/10020303/227567815-bf124a0e-1f28-456f-8cf8-3d86ff04edff.png)
