### ISSUE TITLE
Some devices are missing from the local network.

### ISSUE THREAD

**Issue by dtech77pl** [jokob-sk/Pi.Alert#221]
Some of the devices are missing in the Pi.Alert database. These machines are pingable from the local LAN. 
When I check the pialert_pholus_lastrun.log file these devices are logged into the file. 

02:11:32:2f:e9:17 | 192.168.77.30               | Answer              | _smb._tcp.local. PTR Class:IN "WARSAW-TVHEADEND._smb._tcp.local."
02:11:32:2f:e9:17 | 192.168.77.30               | Answer              | _smb._tcp.local. PTR Class:IN "WARSAW-TVHEADEND._smb._tcp.local."
02:11:32:2f:e9:17 | 192.168.77.30               | Answer              | WARSAW-TVHEADEND._smb._tcp.local. TXT Class:32769 ""
02:11:32:2f:e9:17 | 192.168.77.30               | Answer              | WARSAW-TVHEADEND._smb._tcp.local. TXT Class:32769 ""
SUB-PROCESS KILLED TIMESTAMP: 2023-05-06 21:33:38

But the device list is not visible: 

[http://dtech.home.pl/pub/error.jpg](url)

I'm using the latest stable version on Docker. This docker is set up on Synology NAS. Except for this issue, everything else is working fine. 
This is a great tool, thank you for putting your effort to make it live.

**Comment by jokob-sk** [comment]
Hi there!

What I think is happening (however I'm not too confident of my network knowledge), is that arp-scan (if you are using it to discover your devices) is less aggressive than Pholus, which is a network penetration/testing tool. Currently I don't use Pholus to discover additional devices, only for collecting additional details, such as attempting to get the device name. 

What you can do is you can complement your default `arp-scan` based network discovery with either PiHole or one of the plugins, e.g. SNMP discovery, DHCP leases or Unifi import if you have Unifi based gear. 

Hope this helps,
j

**Comment by dtech77pl** [comment]
Thank you for the information. I tried to connect pi.alert with pi.hole but with no luck. 

Do you have an example of yml file of how this should be done? 

My Pi.Hole is in the separate docker container but I do have access to pihole-FTL.db

**Comment by jokob-sk** [comment]
Hi @dtech77pl !

Thanks for the donation! Really appreciate it!

I don't use PiHole myself, but  it may look something like this (notice the last 2 lines in the volumes section):

```yaml
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - local/path/pialert/config:/home/pi/pialert/config
      - local/path/pialert/db:/home/pi/pialert/db      
      # (optional) useful for debugging if you have issues setting up the container
      - local/path/logs:/home/pi/pialert/front/log
      - local/path/pihole/dhcp.leases:/etc/pihole/dhcp.leases
      - local/pathpihole/pihole-FTL.db:/etc/pihole/pihole-FTL.db
    environment:
      - TZ=Europe/Berlin      
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=20211
```

You'd also then enable the settings `PIHOLE_ACTIVE` and `DHCP_ACTIVE`.
