### ISSUE TITLE
Enable SMTP function, Docker will auto restart .

### ISSUE THREAD

**Issue by zfung03** [jokob-sk/Pi.Alert#279]
**Describe the issue**
Enable SMTP function, Docker will auto restart .

**Paste last few lines from `pialert.log`**

> You can use `tail -20 /home/pi/pialert/front/log/pialert.log`

```
paste_here
```

**Paste your `pialert.conf` (remove personal info)**

```
# General
#---------------------------
ENABLE_ARPSCAN=True
SCAN_SUBNETS=['192.168.16.0/24 --interface=ovs_bond0']
LOG_LEVEL='verbose'
TIMEZONE='Asia/Shanghai'
ENABLE_PLUGINS=True
PIALERT_WEB_PROTECTION=True
PIALERT_WEB_PASSWORD='**********'
INCLUDED_SECTIONS=['internet','new_devices','down_devices','events']
SCAN_CYCLE_MINUTES=5
DAYS_TO_KEEP_EVENTS=90
REPORT_DASHBOARD_URL='http://pi.alert'
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'
UI_LANG='English'
UI_PRESENCE=['online','offline','archived']


# Email
#---------------------------
REPORT_MAIL=True
SMTP_SERVER='192.168.16.8'
SMTP_PORT=25
REPORT_TO='vincent@ABC.com.hk'
REPORT_FROM='Pi.Alert <MW>'
SMTP_SKIP_LOGIN=True
SMTP_USER='pialert@ABC.com.hk'
SMTP_PASS='******'
SMTP_SKIP_TLS=True
SMTP_FORCE_SSL=False
```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 

```
version: "3.9"
services:
  pi.alert:
     container_name: Pi.Alert
     healthcheck:
      test: curl -f http://localhost:17811/ || exit 1
     mem_limit: 2g
     cpu_shares: 768
     security_opt:
      - no-new-privileges:true
     volumes:
      - /volume1/docker/pialert/config:/home/pi/pialert/config:rw
      - /volume1/docker/pialert/db:/home/pi/pialert/db:rw
      - /volume1/docker/pialert/logs:/home/pi/pialert/front/log:rw
     environment:
      TZ: Asia/Shanghai
      PORT: 17811
      HOST_USER_ID: 1026
      HOST_USER_GID: 100
     network_mode: host
     restart: unless-stopped
     image: jokobsk/pi.alert:latest
```

`.env` 

```
paste_here
```

**Screenshots**
![Snipaste_2023-07-04_09-45-57](https://github.com/jokob-sk/Pi.Alert/assets/51111549/0a1649d3-e13d-44fa-88b9-2329de203c3c)
