### ISSUE TITLE
Is there a way to setup the password in the first boot whit a docker env_var?

### ISSUE THREAD

**Issue by sbe-arg** [jokob-sk/Pi.Alert#286]
**Is your feature request related to a problem? Please describe.**
pihole supports setting up the admin password during the first boot

**Describe the solution you'd like**

adding envvar WEBPASSWORD that sets the web password during the first container boot.

```
  pihole:
    container_name: pihole
    hostname: pihole
    image: docker.io/pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      - TZ=Pacific/Auckland
      - WEBPASSWORD=password
    volumes:
      - /var/docker-services/pihole/config:/etc/pihole
      - /var/docker-services/pihole/dnsmasq:/etc/dnsmasq.d
    networks:
      - services
    restart: unless-stopped

  pialert:
    container_name: pialert
    hostname: pialert
    privileged: true
    image: jokobsk/pi.alert
    environment:
      - TZ=Pacific/Auckland
      - WEBPASSWORD=password
    restart: unless-stopped
    volumes:
      - /var/docker-services/pialert/config:/home/pi/pialert/config
      - /var/docker-services/pialert/db:/home/pi/pialert/db
    network_mode: host
```

**Describe alternatives you've considered**
setting up the password manually using exec --it
