### ISSUE TITLE
Unable to load network tree

### ISSUE THREAD

**Issue by Maarten-buelens** [jokob-sk/Pi.Alert#353]
## Describe the issue

When I open the network tab the network tree does not load. this happens because of a recursion error.

while loading the tree the function getChildren gets called which in turn calls itself for each device.
This leads to too much recursion and it exceeds the call stack.
At the moment I have 51 devices.

##  `pialert.conf` 

```
# General
#---------------------------
ENABLE_ARPSCAN=True
SCAN_SUBNETS=['192.168.0.0/24 --interface=ens18']
LOG_LEVEL='debug'
TIMEZONE='Europe/Berlin'
ENABLE_PLUGINS=True
PLUGINS_KEEP_HIST=10000
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD=''
INCLUDED_SECTIONS=['internet','new_devices','down_devices','events']
SCAN_CYCLE_MINUTES=5
REPORT_DASHBOARD_URL='http://pi.alert'
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'
UI_LANG='English'
UI_PRESENCE=['online','offline','archived']
DAYS_TO_KEEP_EVENTS=90
HRS_TO_KEEP_NEWDEV=0
```

## `docker-compose.yml` 

`docker-compose.yml` 

```
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: unless-stopped

    volumes:
      - /home/mb/pialert/config:/home/pi/pialert/config
      - /home/mb/pialert/db:/home/pi/pialert/db      
      - /home/mb/pialert/logs:/home/pi/pialert/front/log
    environment:
      - TZ=Europe/Berlin      
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=20211
```

## Screenshots

firefox
![image](https://github.com/jokob-sk/Pi.Alert/assets/69542912/cd1b230c-46b3-4205-af47-a0eb259fb5d8)
chrome
![image](https://github.com/jokob-sk/Pi.Alert/assets/69542912/fa5f191d-6bef-4cb7-8169-4c98b4d644d7)

## Paste last few lines from `pialert.log`

```
Nothing in logs
