### ISSUE TITLE
Seeing lots of RDNS lookups in my pihole from Pialert

### ISSUE THREAD

**Issue by thefunkygibbon** [jokob-sk/Pi.Alert#395]
Seeing it a LOT recently... see the image of my pihole connections on a busy class C network. 

<img width="620" alt="image" src="https://github.com/jokob-sk/Pi.Alert/assets/19172392/4eb8b4ec-215d-43d4-b64e-80c7388abb47">

the orange colour is pialert... about 1100 queries in each 10 min window.   

queries are like this usually
<img width="315" alt="image" src="https://github.com/jokob-sk/Pi.Alert/assets/19172392/77d0ebd0-623b-45b4-aa8f-8df161490a01">

is there a setting to stop this happening, is there any downside in disabling this?  is it expected behaviour?

also, whilst i'm here,  is there any way of getting rid of all the IPv6 / 0.0.0.0/ random MAC address items which show up as devices within Pialert?   i dont want them there, they have no use to me, it just clutters up my list of actual devices on my home network.

**Comment by jokob-sk** [comment]
Hey @thefunkygibbon ,

It looks like you have Name discovery (Pholus scan) scheduled every 10 minutes. I recommend having it execute on new device discovery or once a day to minimize this kind of traffic. 

I'll need more details regarding the second request.

Thanks in advance,
J

**Comment by thefunkygibbon** [comment]
thanks, but i've checked my pholus options and its not ticked and seemingly set to 4am in the cron 
<img width="553" alt="image" src="https://github.com/jokob-sk/Pi.Alert/assets/19172392/e4d4a20a-f20c-4cc9-bf43-bcd30ef7fde6">

**Comment by jokob-sk** [comment]
Hi there,

Could you please let me know what kind of settings you have enabled?

Thanks,
J

**Comment by thefunkygibbon** [comment]
tbh i'm not sure what has been enabled over defaults.  but looking at the conf file the only ones with "enabled" in the section are nmap (cron timer is set to 2am daily)  and pihole as well as the normal arp

**Comment by jokob-sk** [comment]
HI!

PiHole and Arp-Scan do pretty much the same thing. Can you try to disable arp-scan or increase the delay between scans?

**Comment by jokob-sk** [comment]
Closing as no response

**Comment by thefunkygibbon** [comment]
sorry, i was on holiday last week.   I turned arp-scan off, restarted the container and... still seeing the same figures per 10min interval :-( 

![image](https://github.com/jokob-sk/Pi.Alert/assets/19172392/dcae9f71-bff2-4bdf-9f14-aa881d046cc4)

**Comment by jokob-sk** [comment]
Hey!

I'd recommend disabling all plugins and enabling them one by one. Or try the divide and conquer algorithm. 

This still looks like Pholus name resolver queries. I know you said you disabled it, but can you double-check? I'd recommend posting the whole config (after removing sensitive info) so I can have a look at exactly what's enabled.

**Comment by thefunkygibbon** [comment]
well at the moment i'm literally only using pihole!

**Comment by jokob-sk** [comment]
You can try the dev image to see if the issues is fixed there. I recommend creating a backup of everything first:

```
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert_dev"
    network_mode: "host"
    restart: always
    volumes:
      - ${APP_DATA_LOCATION}/pialert_dev/config:/home/pi/pialert/config
      - ${APP_DATA_LOCATION}/pialert_dev/db:/home/pi/pialert/db
      - ${LOGS_LOCATION}/:/home/pi/pialert/log
    environment:
      - TZ=Europe/Berlin
      - HOST_USER_ID=1036
      - HOST_USER_GID=1000
      - PORT=20211
```
