### ISSUE TITLE
PiAlert Settings Page will not Load After Fresh Container Install

### ISSUE THREAD

**Issue by Com177** [jokob-sk/Pi.Alert#460]
I've installed PiAlert on my Synology DS720+ using Container Manager (aka Docker) and the below YaML file as a template that was originally from [Marius Hosting](https://mariushosting.com/how-to-install-pi-alert-on-your-synology-nas/).  It was work with no problem.  During this time I have been deploying a VLAN for my personal network.  I've been in the process of migrating my devices to their new VLAN subnets and the PiAlert scan was finding erroneous connections with IP 0.0.0.0 that could not be modified, deleted or archived.  I tried rebuilding the container and that didn't work so I uninstalled PiAlert and reinstalled it.  The problem reappeared in a few days so I reinstalled twice more.  The last time I did the reinstall I got a Settings page that had nothing but a SAVE button.  There were absolutely no settings that could be configured. Since I was unable to input the IPs and VLANs to scan the app became useless.  Please refer to [https://community.synology.com/enu/forum/1/post/162747?reply=502652](url) for more information. This is also the post where you discovered my problem on 09/22/23.

[describe your issue]

## Paste your `pialert.conf` (remove personal info)

```
-----------------AUTOGENERATED FILE-----------------#
#                                                    
#
#         Generated:  2023-08-14_08-22-11            #
#                                                    
#
#   Config file for the LAN intruder detection app:  
#
#      https://github.com/jokob-sk/Pi.Alert          
#
# 
                                                   
#
#-----------------AUTOGENERATED FILE-----------------
#


# General
#---------------------------ENABLE_ARPSCAN=True
SCAN_SUBNETS=['192.168.1.0/24 --interface=eth1','192.168.1.0/24 --interface=eth0']
LOG_LEVEL='verbose'
TIMEZONE='America/New_York'
ENABLE_PLUGINS=True
PLUGINS_KEEP_HIST=10000
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD='8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92'
INCLUDED_SECTIONS=['internet']
SCAN_CYCLE_MINUTES=5
REPORT_DASHBOARD_URL='http://pi.alert'
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'
UI_LANG='English'
UI_PRESENCE=['archived']
DAYS_TO_KEEP_EVENTS=90
HRS_TO_KEEP_NEWDEV=0

# Email
#---------------------------REPORT_MAIL=True
SMTP_SERVER='mail.<my domain.com>'
SMTP_PORT=465
REPORT_TO='<my@Email.com>'
REPORT_FROM='Pi.Alert <my@Email.com>'
SMTP_SKIP_LOGIN=FalseSMTP_USER='<my@Email.com>'
SMTP_PASS='PRIVATE1'
SMTP_SKIP_TLS=False
SMTP_FORCE_SSL=False

# Webhooks#---------------------------REPORT_WEBHOOK=False

WEBHOOK_URL='http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD='json'

WEBHOOK_REQUEST_METHOD='GET'
WEBHOOK_SIZE=1024

# Apprise#---------------------------REPORT_APPRISE=False
APPRISE_HOST='http://localhost:8000/notify'

APPRISE_URL='mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'
APPRISE_PAYLOAD='html'

# NTFY#---------------------------REPORT_NTFY=False
NTFY_HOST='https://ntfy.sh'
NTFY_TOPIC='replace_my_secure_topicname_91h889f28'
NTFY_USER='user'
NTFY_PASSWORD='passw0rd'

# PUSHSAFER#---------------------------REPORT_PUSHSAFER=False
PUSHSAFER_TOKEN='ApiKey'

# MQTT#---------------------------REPORT_MQTT=False
MQTT_BROKER='192.168.1.2'
MQTT_PORT=1883
MQTT_USER='mqtt'
MQTT_PASSWORD='passw0rd'
MQTT_QOS=0
MQTT_DELAY_SEC=2

# DynDNS#---------------------------DDNS_ACTIVE=False
DDNS_DOMAIN='your_domain.freeddns.org'
DDNS_USER='dynu_user'
DDNS_PASSWORD='A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL='https://api.dynu.com/nic/update?'


# PiHole#---------------------------PIHOLE_ACTIVE=False
DHCP_ACTIVE=False

# Pholus#---------------------------PHOLUS_ACTIVE=False
PHOLUS_TIMEOUT=120
PHOLUS_FORCE=False
PHOLUS_RUN='once'
PHOLUS_RUN_TIMEOUT=600
PHOLUS_RUN_SCHD='0 4 * * *'
PHOLUS_DAYS_DATA=7

# Nmap#---------------------------NMAP_ACTIVE=True
NMAP_TIMEOUT=150
NMAP_RUN='disabled'
NMAP_RUN_SCHD='0 2 * * *'
NMAP_ARGS='-p -10000'

# API#---------------------------API_CUSTOM_SQL='SELECT * FROM Devices WHERE dev_PresentLastScan = 0'

# DHCPLSS#---------------------------DHCPLSS_RUN='disabled'
DHCPLSS_CMD='python3 /home/pi/pialert/front/plugins/dhcp_leases/script.py paths={paths}'
DHCPLSS_paths_to_check=['/mnt/dhcp1.leases','/mnt/dhcp2.leases']
DHCPLSS_RUN_SCHD='0 2 * * *'
DHCPLSS_RUN_TIMEOUT=5
DHCPLSS_WATCH=['Watched_Value1','Watched_Value4']
DHCPLSS_REPORT_ON=['new','watched-changed']

# DHCPSRVS#---------------------------DHCPSRVS_RUN='disabled'
DHCPSRVS_CMD='python3 /home/pi/pialert/front/plugins/dhcp_servers/script.py'
DHCPSRVS_RUN_SCHD='0 2 * * *'
DHCPSRVS_RUN_TIMEOUT=5
DHCPSRVS_WATCH=['Watched_Value1']
DHCPSRVS_REPORT_ON=['new','watched-changed']

# NEWDEV#---------------------------NEWDEV_dev_MAC=''
NEWDEV_dev_Name='(unknown)'
NEWDEV_dev_Vendor=''
NEWDEV_dev_FirstConnection=''
NEWDEV_dev_LastConnection=''
NEWDEV_dev_LastIP=''
NEWDEV_dev_SkipRepeated=0
NEWDEV_dev_LastNotification=''
NEWDEV_dev_Network_Node_port='0'

# NMAPSRV#---------------------------NMAPSRV_RUN='disabled'
NMAPSRV_CMD='SELECT  ns.MAC as Object_PrimaryID, cast({s-quote}http://{s-quote} || dv.dev_LastIP as VARCHAR(100)) || {s-quote}:{s-quote} || cast( SUBSTR(ns.Port ,0, INSTR(ns.Port , {s-quote}/{s-quote})) as VARCHAR(100)) as Object_SecondaryID,  datetime() as DateTime,  ns.Service as Watched_Value1, ns.State as Watched_Value2, dv.dev_Name as Watched_Value3,        {s-quote}null{s-quote} as Watched_Value4,        ns.Extra as Extra, ns.MAC as ForeignKey FROM (SELECT * FROM Nmap_Scan) ns left JOIN (SELECT dev_Name, dev_MAC, dev_LastIP FROM Devices) dv  ON ns.MAC = dv.dev_MAC'
NMAPSRV_RUN_SCHD='0 2 * * *'
NMAPSRV_WATCH=['Watched_Value1']
NMAPSRV_REPORT_ON=['new','watched-changed']

# SNMPDSC#---------------------------SNMPDSC_RUN='disabled'
SNMPDSC_CMD='python3 /home/pi/pialert/front/plugins/snmp_discovery/script.py routers={s-quote}{routers}{s-quote}'
SNMPDSC_routers=['snmpwalk -v 2c -c public -OXsq 192.168.1.1 .1.3.6.1.2.1.3.1.1.2']
SNMPDSC_RUN_SCHD='0 2 * * *'
SNMPDSC_RUN_TIMEOUT=5
SNMPDSC_WATCH=['Watched_Value1']
SNMPDSC_REPORT_ON=['new','watched-changed']

# UNDIS#---------------------------UNDIS_RUN='disabled'
UNDIS_CMD='python3 /home/pi/pialert/front/plugins/undiscoverables/script.py devices={devices}'
UNDIS_RUN_TIMEOUT=10
UNDIS_devices_to_import=['dummy_router']

# UNFIMP#---------------------------UNFIMP_RUN='disabled'
UNFIMP_CMD='python3 /home/pi/pialert/front/plugins/unifi_import/script.py username={username} password={password}  host={host} sites={sites}  protocol={protocol} port={port} version={version}'
UNFIMP_username=''
UNFIMP_password=''
UNFIMP_protocol='https://'
UNFIMP_host='192.168.1.1'
UNFIMP_port='8443'
UNFIMP_version=''
UNFIMP_sites=['default']
UNFIMP_RUN_SCHD='0 2 * * *'
UNFIMP_RUN_TIMEOUT=5
UNFIMP_WATCH=['Watched_Value1','Watched_Value4']
UNFIMP_REPORT_ON=['new','watched-changed']

# WEBMON#---------------------------WEBMON_RUN='disabled'
WEBMON_CMD='python3 /home/pi/pialert/front/plugins/website_monitor/script.py urls={urls}'
WEBMON_RUN_SCHD='0 2 * * *'
WEBMON_API_SQL='SELECT * FROM plugin_website_monitor'
WEBMON_RUN_TIMEOUT=5
WEBMON_WATCH=['Watched_Value1']
WEBMON_REPORT_ON=['new','watched-changed']
WEBMON_urls_to_check=['https://google.com','https://duck.com']
WEBMON_SQL_internet_ip='SELECT dev_LastIP FROM Devices WHERE dev_MAC = {s-quote}Internet{s-quote}'

#-------------------IMPORTANT INFO-------------------#
#   This file is ingested by a python script, so if  #
#        modified it needs to use python syntax      
#
#-------------------IMPORTANT INFO-------------------#
```

## Paste your `docker-compose.yml` and `.env` (remove personal info)

```
version: "3.9"
services:
  pi.alert:
     container_name: Pi.Alert
     healthcheck:
      test: curl -f http://localhost:17811/ || exit 1
     mem_limit: 2g
     cpu_shares: 768
     security_opt:
      - no-new-privileges:true
     volumes:
      - /volume1/docker/pialert/config:/home/pi/pialert/config:rw
      - /volume1/docker/pialert/db:/home/pi/pialert/db:rw
      - /volume1/docker/pialert/logs:/home/pi/pialert/front/log:rw
     environment:
      TZ: America/New_York
      PORT: 17811
      HOST_USER_ID: 1026
      HOST_USER_GID: 100
     network_mode: host
     restart: on-failure:5
     image: "jokobsk/pi.alert:latest"
     SCAN_SUBNETS= ['192.168.1.0/24 --interface=eth0']
     SCAN_SUBNETS    = ['192.168.1.0/24 --interface=eth0', '192.168.1.0/24 --interface=eth1 -vlan=107']
     SCAN_SUBNETS   ='199.18.91.0/24 --interface=eth0 -vlan-91'
     SCAN_SUBNETS   ='199.18.91.0/24 --interface=eth1 -vlan=91'
     SCAN_SUBNETS   ='222.139.110.0/24 --interface=eth0 -vlan=110'
     SCAN_SUBNETS   ='222.139.110.0/24 --interface=eth1 -vlan=110'
     SCAN_SUBNETS   ='118.68.250.0/24 --interface=eth0 -vlan=250'
     SCAN_SUBNETS   ='118.68.250.0/24 --interface=eth1 -vlan=250'
    # PIHOLE_ACTIVE:/volume1/docker/pialert/pihole-FTL.db:/home/pi/pialert/pihole-FTL:rw
    # DHCP_ACTIVE:/volume1/docker/pialert/dhcp.leases:/home/pi/pialert/dhcp.leases:rw
```
## Paste your `YAML` file

```
version: "3.9"
services:
  pi.alert:
     container_name: Pi.Alert
     healthcheck:
      test: curl -f http://localhost:17811/ || exit 1
     mem_limit: 2g
     cpu_shares: 768
     security_opt:
      - no-new-privileges:true
     volumes:
      - /volume1/docker/pialert/config:/home/pi/pialert/config:rw
      - /volume1/docker/pialert/db:/home/pi/pialert/db:rw
      - /volume1/docker/pialert/logs:/home/pi/pialert/front/log:rw
     environment:
      TZ: America/New_York
      PORT: 17811
      HOST_USER_ID: 1026
      HOST_USER_GID: 100
     network_mode: host
     restart: on-failure:5
     image: jokobsk/pi.alert:latest

```

`.env` 

```
I cannot find if one was created or not.
```

## Screenshots

![image](https://github.com/jokob-sk/Pi.Alert/assets/146547765/22138f85-82d2-4446-b366-edf4b96a7af2)

## Paste last few lines from `pialert.log`

All logs were erased with uninstalls.

```bash

# paste code below 

```

**Comment by jokob-sk** [comment]
Hi @Com177 👋
Thanks so much for adding such a detailed description of your issue. This will help me figure it out quicker.

The good thing is that I think this is a minor issue and probably javascript related. To troubleshoot, can I ask you to do the following?

1. Please send me a screenshot of the browser console and any errors you can find (Look at the [screenshot here](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_INVALID_JSON.md) if you have troubles finding it)
2. Can you delete any older images you may have downloaded and download the latest one as I think there was a settings bug fixed in the last few weeks. 
3. Can you check the `pialert.log` files after you set the log to the debug level? It's OK not to have the old logs, the new ones help a lot too to see if something prevents settings from loading. Last few lines should be enough.
4. If above doesn't help, can you try the `_dev` image (see example below)?

```yaml
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert_dev"
    network_mode: "host"
    restart: always
    volumes:
      - ${APP_DATA_LOCATION}/pialert_dev/config:/home/pi/pialert/config
      - ${APP_DATA_LOCATION}/pialert_dev/db:/home/pi/pialert/db
      - ${LOGS_LOCATION}/:/home/pi/pialert/log
    environment:
      - TZ=Europe/Berlin
      - HOST_USER_ID=1036
      - HOST_USER_GID=1000
      - PORT=20211
```

More [debugging tips](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md) if needed.

Thanks for the details in advance,
j
