### ISSUE TITLE
[bug] Root network node allows parent node selection

### ISSUE THREAD

**Issue by Minituff** [jokob-sk/Pi.Alert#467]
## The issue
No network diagram. I followed the guide [here](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/NETWORK_TREE.md) to add an `internet` node, but I still don't see a diagram.

I am pretty sure I am missing something simple, but I can't figure it out.

## docker-compose.yml

```yaml
---
version: "3"
services:
  pialert:
    container_name: pialert
    hostname: pialert
    image: "jokobsk/pi.alert:latest"   # image: "jokobsk/pi.alert_dev:latest"     
    restart: unless-stopped
    ports:
      - "80:20211/tcp"
    volumes:
      - /opt/docker_volumes/pialert/config:/home/pi/pialert/config
      - /opt/docker_volumes/pialert/db:/home/pi/pialert/db
      - /opt/docker_volumes/pialert/logs:/home/pi/pialert/front/log # (optional) useful for debugging if you have issues setting up the container
    environment:
      - TZ=America/Los_Angeles      
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=20211
    networks:
      local_net:
        ipv4_address: 192.168.1.66

networks:
  local_net:
    external: true
    name: local_net
```

## Screenshots

<img width="1078" alt="Screenshot 2023-10-04 at 10 50 57 AM" src="https://github.com/jokob-sk/Pi.Alert/assets/8152401/cd6c7d4d-7b3d-4ef4-9569-694b149c9007">

## Last few lines from `pialert.log`

```bash
[2023-10-04_10-50-07] 
   Settings saved to the <code>pialert.conf</code> file.
   
   A time-stamped backup of the previous file created. 
   
    Reloading...
```
