### ISSUE TITLE
Database backup error

### ISSUE THREAD

**Issue by rodrigohess** [jokob-sk/Pi.Alert#486]
Hello, when I try to create a DB backup I get the following message: "The original data base could not be saved".

![image](https://github.com/jokob-sk/Pi.Alert/assets/55641542/ee0764d6-f609-4055-8cec-cc2e4b58ebac)

## Paste your `pialert.conf` (remove personal info)

```
# General
#---------------------------
LOG_LEVEL='verbose'
LOG_LEVEL__metadata="{}"
TIMEZONE='America/Santiago'
TIMEZONE__metadata="{}"
PLUGINS_KEEP_HIST=250
PLUGINS_KEEP_HIST__metadata="{}"
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PROTECTION__metadata="{}"
PIALERT_WEB_PASSWORD='xxx
PIALERT_WEB_PASSWORD__metadata="{}"
INCLUDED_SECTIONS=['new_devices','down_devices','events']
INCLUDED_SECTIONS__metadata="{}"
REPORT_DASHBOARD_URL='http://pi.alert'
REPORT_DASHBOARD_URL__metadata="{}"
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'
DIG_GET_IP_ARG__metadata="{}"
UI_LANG='English'
UI_LANG__metadata="{}"
UI_PRESENCE=['online','offline','archived']
UI_PRESENCE__metadata="{}"
DAYS_TO_KEEP_EVENTS=90
DAYS_TO_KEEP_EVENTS__metadata="{}"
HRS_TO_KEEP_NEWDEV=0
HRS_TO_KEEP_NEWDEV__metadata="{}"
API_CUSTOM_SQL='SELECT * FROM Devices WHERE dev_PresentLastScan = 0'
API_CUSTOM_SQL__metadata="{}"
NETWORK_DEVICE_TYPES=['AP','Gateway','Firewall','Hypervisor','Powerline','Switch','WLAN','PLC','Router','USB LAN Adapter','USB WIFI Adapter','Internet']
NETWORK_DEVICE_TYPES__metadata="{}"

```

## Paste your `docker-compose.yml` and `.env` (remove personal info)

`docker-compose.yml` 

```
version: "3.9"
services:
  pialert:
    container_name: Pi.Alert
    image: jokobsk/pi.alert:latest
    restart: on-failure:5
    network_mode: host
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/lib/docker/data-gfs/pialert/config:/home/pi/pialert/config:rw
      - /var/lib/docker/data-gfs/pialert/db:/home/pi/pialert/db:rw
      - /var/lib/docker/data-gfs/pialert/logs:/home/pi/pialert/front/log:rw
    ports:
      - 17811:17811
    environment:
      TZ: America/Santiago
      PORT: 17811
      HOST_USER_ID: 1000
      HOST_USER_GID: 100
#    networks:
#      - outside
    deploy:
      placement:
        constraints: 
          - node.role == manager
```
## Screenshots

![image](https://github.com/jokob-sk/Pi.Alert/assets/55641542/bf5aeb86-5044-4a2c-af61-f434408463c3)

## Paste last few lines from `pialert.log`

10:12:37 [MAIN] waiting to start next loop
10:12:42 [MAIN] waiting to start next loop
10:12:47 [Plugins] ---------------------------------------------
10:12:47 [Plugins] display_name: Arp-Scan (Network scan)
10:12:47 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/arp_scan/script.py userSubnets={subnets}
10:12:47 [ARP Scan] In script 
10:12:47 [ARP Scan] values.userSubnets: ["userSubnets=b'MTkyLjE2OC4xLjk5LzI0IC0taW50ZXJmYWNlPWVucDNzMA=='"]
10:12:47 [ARP Scan] userSubnetsParamBase64: 'MTkyLjE2OC4xLjk5LzI0IC0taW50ZXJmYWNlPWVucDNzMA=='
10:12:47 [ARP Scan] userSubnetsParam: 192.168.x.xx/24 --interface=xxx
