### ISSUE TITLE
[help] 📢 Help me test the next release

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#489]
Hi 👋,

Anyone reading - if you have a few minutes try testing the _dev container. 

I changed the whole installation process, and notification internals and rewrote all notifications into plugins. There probably will be bugs 😅

### 🐛 Currently known issues on the `_dev` image:

* Pholus Name matching not working on the first cycle (?)

I'm getting closer to a release and not to break your setups, it would be great to get some early feedback:

```yaml
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert_dev"
    network_mode: "host"
    restart: always
    volumes:
      - ${APP_DATA_LOCATION}/pialert_dev/config:/home/pi/pialert/config
      - ${APP_DATA_LOCATION}/pialert_dev/db:/home/pi/pialert/db
      - ${LOGS_LOCATION}/:/home/pi/pialert/log
    environment:
      - TZ=Europe/Berlin
      - HOST_USER_ID=1036
      - HOST_USER_GID=1000
      - PORT=20211
```

Thanks a bunch in advance! 🙏
j
