### ISSUE TITLE
Undocumented USER env variable and permission issues

### ISSUE THREAD

**Issue by eltiel** [jokob-sk/Pi.Alert#78]
When I tried starting up the image, the log shows:

`We need USER to be set!`

I've already set HOST_USER_ID and HOST_USER_GID

------------------

Secondly, I think I'm having permission issues despite having set the db folder to 777. Following the guide, I can't `chown root:www-data` the folder as I'm on Synology and there's no www-data group.

**Comment by jokob-sk** [comment]
Hi there

Thanks for using my image :) 

Did you follow the instructions outlined in the readme? https://github.com/jokob-sk/Pi.Alert/tree/main/dockerfiles

The image should run without issues even if you omit the "HOST_USER_ID" and "HOST_GROUP_ID" variables, they are only used for mapping the permissions for the DB. You can alternatively use the CSV export for backup. 

Are you using docker-compose for setting up the container or a different approach? If a different approach, please post yous command below (replace sensitive info). 

I'm running the container as we speak with the following docker-compose file:

```yaml
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: always
    volumes:
      - my/path/pialert/config:/home/pi/pialert/config
      - my/path2/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
    environment:
      - TZ=Europe/Berlin
      - PORT=20211
      - HOST_USER_ID=1055
      - HOST_USER_GID=1000
```

I just run `docker-compose up`

The `We need USER to be set!` error comes form this file: https://github.com/jokob-sk/Pi.Alert/blob/3d5895265433978f49f8e054178df4d1685c0b53/dockerfiles/user-mapping.sh#L4

Which in turn relies on the variable set in the Dockerfile itself:

https://github.com/jokob-sk/Pi.Alert/blob/3d5895265433978f49f8e054178df4d1685c0b53/Dockerfile#L4

Did you modify the Dockerfile by any chance? If yes, can you please try to use the image from DockerHub instead to verify it's working? https://registry.hub.docker.com/r/jokobsk/pi.alert

>Secondly, I think I'm having permission issues despite having set the db folder to 777. Following the guide, I can't chown root:www-data the folder as I'm on Synology and there's no www-data group.

These instructions only apply for bare-metal install, which is not supported in this fork. Only the docker-image based approach is as outlined in the readme here:  https://github.com/jokob-sk/Pi.Alert#installation

> [...] Following the guide, [...]

Can you please link which guide you are following? You still should be able to SSH into the container to perform a CHOWN inside of it:

`sudo docker exec -it pialert /bin/bash` would open the terminal inside of the container.
