### ISSUE TITLE
Solve DB backup when running in docker

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#9]
Based on: https://github.com/jokob-sk/Docker-Image-for-Pi.Alert/issues/2

**Comment by Macleykun** [comment]
heya, can ya try and test if the following helps ya access the db folder + make it persistent?

```
chmod -R +x db/
docker run -v ${PWD}/db/:/home/pi/pialert/db/ -p 85:20211/tcp test
```
the pwd is to give it an absolute path so that docker understand's it's not a name (not accessible by host theoretically)

I couldn't write to the db, if you believe this is correct i can tell ya maybe a bit more about volume and such :) (and why they confusing probably).

**Comment by jokob-sk** [comment]
I think we can close this. The following docker-compose setup mapping the db file directly works fine on my end (making sure the db is writable):

```
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: always
    volumes:
      - /docker_appdata/pialert/config:/home/pi/pialert/config
      - /docker_appdata/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
```
